# Gradle ???? (ForgeGradle ????????????? 3G)
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Java ?? (?? Forge 1.20.1 ???? Java 17??????? JDK 25)
# ?????? JDK 17???????????????????????????? Gradle ????? JDK 17
# org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-17.0.11.9-hotspot

# ??? Minecraft & Forge ?? (Forge ????) ???
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# ??? Mod ?? (? Fabric ?????) ???
mod_id=anythingbutfish
mod_name=AnythingButFish
mod_license=LGPLv3
mod_version=23.8
mod_group_id=io.github.lithum12
mod_authors=LithumC
mod_description=Replaces vanilla fishing loot with completely random items, entities, and experience orbs. Who knows what you'll reel in next?

# YACL for Forge
yacl_version=3.6.5+1.20.1-forge