modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"

[[mods]]
modId="anythingbutfish"
version="23.8"
displayName="AnythingButFish"
authors="LithumC"
itemIcon="minecraft:fishing_rod"
description='''
Replaces vanilla fishing loot with completely random items, entities, and experience orbs.
'''

[[dependencies.anythingbutfish]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.anythingbutfish]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="anythingbutfish.mixins.json"